version: 2.1

commands:
  setup-env:
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: lein with-profile -dev,+test,+ci deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

executors:
  lein-executor:
    docker:
      - image: circleci/clojure:openjdk-8-lein-2.9.1
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor: lein-executor
    steps:
      - setup-env
      - run:
          name: 'Run JVM tests, reporting coverage'
          command: lein with-profile -dev,+test trampoline cloverage --lcov --junit -o coverage/
      - run:
          name: 'Ensure production isolation, check for boxed math'
          command: lein with-profile -dev,+check check
      - store_test_results:
          path: ~/repo/coverage
      - store_artifacts:
          path: ~/repo/coverage
  deploy:
    executor: lein-executor
    steps:
      - setup-env
      - run:
          name: import GPG key
          command: echo -e "$GPG_KEY_V2" | gpg --import
      - run:
          name: Perform pre-release sanity check
          command: lein with-profile -dev,+ci run -m nedap.ci.release-workflow.api sanity-check
      - run:
          name: release to JFrog
          command: lein deploy
          
workflows:
  version: 2
  CircleCI:
    jobs:
      - build:
          context: JFrog
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
      - deploy:
          context: JFrog
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+(-alpha\d+)?$/
